# Project Name: AO3-Bookmark chrome extension

# Aim: Creating vectors out of the user's bookmarks and generating a vector containing the recommended search params using similarity search

# Extracting our data from the AO3 website

In [1]:
import requests
from bs4 import BeautifulSoup
import json

url = "https://archiveofourown.org/users/rounakag/bookmarks"
response = requests.get(url = url)
data = response.content
# Function to extract the bookmark data
def extract_bookmark_data(html_content):
    soup = BeautifulSoup(html_content, 'html.parser')

    bookmarks = []

    for bookmark in soup.select('li.bookmark.blurb.group'):
        # Extract the author's name
        author = bookmark.select_one('div.header.module h4 a[rel="author"]').text if bookmark.select_one(
            'div.header.module h4 a[rel="author"]') else 'Unknown'

       
        tags = [tag.text for tag in bookmark.select('.tags.commas li a.tag')]


        user_set_tags = [tag.text for tag in bookmark.select('.meta.tags.commas li a.tag')]

       
        genres = [genre.text for genre in bookmark.select('h5.fandoms.heading a.tag')]

        
        bookmarks.append({
            "author's name": author,
            'tags': tags,  # original tags + the user-set tags
            'genres': genres
        })

    return bookmarks

#print(extract_bookmark_data(data))

for i in range(5):
    print(extract_bookmark_data(data)[i]["author's name"])
    print(extract_bookmark_data(data)[i]['genres'])
    print(extract_bookmark_data(data)[i]['tags'])
    print("\n")





sceneohscene
['Suits (US TV)']
['Creator Chose Not To Use Archive Warnings', 'Donna Paulsen & Harvey Specter', 'Louis Litt & Mike Ross', 'Louis Litt & Harvey Specter', 'Louis Litt & Donna Paulsen', 'Mike Ross & Rachel Zane', 'Donna Paulsen', 'Harvey Specter', 'Rachel Zane', 'Mike Ross', 'Louis Litt', 'Original Female Character(s)', 'Married Couple', 'Friendship', 'Birthday Presents', 'Best Friends', 'Team as Family', 'Family Fluff', 'One Shot Collection', 'Suits (US TV)', 'Harvey Specter', 'Team as Family', 'Friendship']


miamourstarchaser
['Harry Potter - J. K. Rowling', 'Fear Street Trilogy (Movies 2021)']
['Graphic Depictions Of Violence', 'Major Character Death', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Alice Longbottom/Frank Longbottom', 'Barty Crouch Jr./Evan Rosier', 'Draco Malfoy/Harry Potter', 'Sirius Black', 'Regulus Black', 'James Potter', 'Remus Lupin', 'Frank Longbottom', 'Alice Longbottom', 'Barty Crouch Jr.', 'Evan Rosier', 'Draco Malfoy', 'Harry Potte

# Making a dataframe of the extracted data

In [13]:
author_list = [extract_bookmark_data(data)[i]["author's name"]for i in range(5)]
genres_list = [extract_bookmark_data(data)[i]["genres"] for i in range(5)]
tags_list = [extract_bookmark_data(data)[i]["tags"] for i in range(5)]
print(author_list, "\n")
print(genres_list, "\n")
print(tags_list)

['sceneohscene', 'miamourstarchaser', 'iiSaturnGhxst', 'ShatteredSilverIris', 'MakerofTales'] 

[['Suits (US TV)'], ['Harry Potter - J. K. Rowling', 'Fear Street Trilogy (Movies 2021)'], ['Harry Potter - J. K. Rowling'], ['Harry Potter - J. K. Rowling'], ['Naruto (Anime & Manga)', '?']] 

[['Creator Chose Not To Use Archive Warnings', 'Donna Paulsen & Harvey Specter', 'Louis Litt & Mike Ross', 'Louis Litt & Harvey Specter', 'Louis Litt & Donna Paulsen', 'Mike Ross & Rachel Zane', 'Donna Paulsen', 'Harvey Specter', 'Rachel Zane', 'Mike Ross', 'Louis Litt', 'Original Female Character(s)', 'Married Couple', 'Friendship', 'Birthday Presents', 'Best Friends', 'Team as Family', 'Family Fluff', 'One Shot Collection', 'Suits (US TV)', 'Harvey Specter', 'Team as Family', 'Friendship'], ['Graphic Depictions Of Violence', 'Major Character Death', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Alice Longbottom/Frank Longbottom', 'Barty Crouch Jr./Evan Rosier', 'Draco Malfoy/Harry Potte

# Exploring the dataset

In [17]:
for i in range(5):
    data = {"author_name":author_list[i],"tags_name":tags_list[i],"genre_name":genres_list[i]}
    print("\n")
    print(data)



{'author_name': 'sceneohscene', 'tags_name': ['Creator Chose Not To Use Archive Warnings', 'Donna Paulsen & Harvey Specter', 'Louis Litt & Mike Ross', 'Louis Litt & Harvey Specter', 'Louis Litt & Donna Paulsen', 'Mike Ross & Rachel Zane', 'Donna Paulsen', 'Harvey Specter', 'Rachel Zane', 'Mike Ross', 'Louis Litt', 'Original Female Character(s)', 'Married Couple', 'Friendship', 'Birthday Presents', 'Best Friends', 'Team as Family', 'Family Fluff', 'One Shot Collection', 'Suits (US TV)', 'Harvey Specter', 'Team as Family', 'Friendship'], 'genre_name': ['Suits (US TV)']}


{'author_name': 'miamourstarchaser', 'tags_name': ['Graphic Depictions Of Violence', 'Major Character Death', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Alice Longbottom/Frank Longbottom', 'Barty Crouch Jr./Evan Rosier', 'Draco Malfoy/Harry Potter', 'Sirius Black', 'Regulus Black', 'James Potter', 'Remus Lupin', 'Frank Longbottom', 'Alice Longbottom', 'Barty Crouch Jr.', 'Evan Rosier', 'Draco Malfoy', 

In [18]:

sample_bookmark_data = [
    {"author_name":"sceneohscene", 
     "tags":"['Creator Chose Not To Use Archive Warnings', 'Donna Paulsen & Harvey Specter', 'Louis Litt & Mike Ross', 'Louis Litt & Harvey Specter', 'Louis Litt & Donna Paulsen', 'Mike Ross & Rachel Zane', 'Donna Paulsen', 'Harvey Specter', 'Rachel Zane', 'Mike Ross', 'Louis Litt', 'Original Female Character(s)', 'Married Couple', 'Friendship', 'Birthday Presents', 'Best Friends', 'Team as Family', 'Family Fluff', 'One Shot Collection', 'Suits (US TV)', 'Harvey Specter', 'Team as Family', 'Friendship']", 
     "genres":"['Harry Potter - J. K. Rowling', 'Fear Street Trilogy (Movies 2021)']"
    },
    {"author_name":"miamourstarchaser",
     "tags":"['Graphic Depictions Of Violence', 'Major Character Death', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Alice Longbottom/Frank Longbottom', 'Barty Crouch Jr./Evan Rosier', 'Draco Malfoy/Harry Potter', 'Sirius Black', 'Regulus Black', 'James Potter', 'Remus Lupin', 'Frank Longbottom', 'Alice Longbottom', 'Barty Crouch Jr.', 'Evan Rosier', 'Draco Malfoy', 'Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Marauders Era (Harry Potter)', 'Movie: Fear Street Part 2: 1978', 'Crossover', 'Alternate Universe', 'Summer Camp', 'Horror', 'Murder', 'Brother Angst', \"I've been watching fear street pt 2 every day this week\", 'Jegulus', 'wolfstar', 'Fralice', 'Rosekiller', 'Drarry', 'Alternate Universe', 'Marauders Era (Harry Potter)', 'Horror']",
     "genres":"['Harry Potter - J. K. Rowling', 'Fear Street Trilogy (Movies 2021)']"
    },
    {"author_name":"iiSaturnGhxst",
     "tags":"['Major Character Death', 'No Archive Warnings Apply', 'Sirius Black/Remus Lupin', 'Sirius Black & Remus Lupin', 'Harry Potter & Severus Snape', 'Luna Lovegood/Harry Potter', 'Sirius Black & James Potter', 'James Potter', 'Sirius Black', 'Hermione Granger', 'Remus Lupin', 'Molly Weasley', 'Ron Weasley', 'Arthur Weasley', 'Weasley Family (Harry Potter)', 'Severus Snape', 'Albus Dumbledore', 'Professor McGonagall', 'Dolores Umbridge', 'Nymphadora Tonks', 'Luna Lovegood', 'Harry Potter', 'Dursley Family (Harry Potter)', 'Abused Harry Potter', 'Depressed Harry Potter', 'Worried James Potter', 'Albus Dumbledore Bashing', 'Molly Weasley Bashing', 'It Gets Worse Before It Gets Better', 'Order of the Phoenix (Harry Potter)', 'Abused Harry Potter', 'Depressed Harry Potter', 'Albus Dumbledore Bashing', 'Order of the Phoenix (Harry Potter)']",
     "genres":"['Harry Potter - J. K. Rowling']"
    },
    {"author_name":"ShatteredSilverIris",
     "tags":"['Creator Chose Not To Use Archive Warnings', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Barty Crouch Jr./Evan Rosier', 'Regulus Black & Remus Lupin', 'Minor or Background Relationship(s)', 'Regulus Black', 'James Potter', 'Sirius Black', 'Remus Lupin', 'Peter Pettigrew', 'Evan Rosier', 'Barty Crouch Jr.', 'Lily Evans Potter', 'Marlene McKinnon', 'Pandora Lovegood', 'Dorcas Meadowes', 'Mary Macdonald (Harry Potter)', 'Severus Snape', 'Enemies to Lovers', 'Blind Character', 'Scars', 'Drinking Games', 'Truth or Dare', 'Spin the Bottle', 'Abusive Walburga Black', 'Abusive Parents', 'Alcohol', 'Cigarettes', 'Sad Regulus Black', 'Good Friend Barty Crouch Jr.', 'Good Friend Evan Rosier', 'Sibling Bonding', 'Regulus Black Needs a Hug', 'Non-binary Sirius Black', 'Sexuality Crisis', 'Gender Identity', 'Asexual Peter Pettigrew', 'Good Friend Remus Lupin', 'Hogwarts Inter-House Unity', 'Friends to Lovers', 'First Kiss', 'Platonic Kissing', 'Remus Lupin is So Done', 'Regulus Black & Remus Lupin Friendship', 'Brotherly Bonding', 'Barty Crouch Jr. is a Little Shit', 'Sirius Black is a Little Shit', 'Protective Sirius Black', 'Oblivious Remus Lupin', 'Oblivious Sirius Black', 'No beta we die like the marauders', 'Alternate Universe - No Voldemort', 'Never Have I Ever', 'Alternate Universe - Everyone Lives/Nobody Dies', 'We do not support jkr', 'Pottercest (Harry Potter)', 'Sirius Black/Remus Lupin', 'Severus Snape']",
     "genres":"['Harry Potter - J. K. Rowling']"
    },
    {"author_name":"MakerofTales",
     "tags":"['Graphic Depictions Of Violence', 'Major Character Death', 'Underage', 'Namikaze Minato/Uzumaki Kushina', 'Naruko Uzumaki & Her ANBU', 'Uzumaki Naruko', 'Hatake Kakashi', 'Sarutobi Hiruzen', 'Senju Hashirama', 'Teuchi (Naruto)', 'Jiraiya (Naruto)', 'Shimura Danzou', 'Yamato | Tenzou', 'Nagato | Pain', 'Zetsu (Naruto)', 'Namiashi Raidou', 'Namikaze Minato', 'Uchiha Itachi', 'Shiranui Genma', 'Anbu Characters (Naruto)', 'Original Anbu Character(s) (Naruto)', 'Hyuuga Hinata', 'Aburame Shino', 'Uchiha Sasuke', 'Ami (Naruto)', 'Nara Shikamaru', 'Akimichi Chouji', 'Umino Iruka', 'Oonoki (Naruto)', 'A | Fourth Raikage', 'Killer Bee (Naruto)', 'Terumi Mei', 'Karatachi Yagura', 'Sai (Naruto)', 'Haruno Sakura', 'Tobi (Naruto)', 'Reincarnation', 'Alternate Universe', 'Crossover', 'Cross-Posted on FanFiction.Net', 'Genderbending', 'Training', 'Chakra (Naruto)', 'Female Uzumaki Naruto', 'Academy', 'War', 'Jinchuuriki (Naruto)', 'Insanity', 'Bijuu | Tailed Beasts (Naruto)', 'Alternate Universe - Canon Divergence', 'Minato Namikaze is insane', 'Naruko is Insane', 'Ramen', 'Genius Naruko Uzumaki', 'Tricky Naruko Uzumaki', 'Henge no Jutsu | Transformation Technique', 'Kage Bunshin | Shadow Clones', 'Shinobi', 'Shinobi Politics (Naruto)', 'Infiltration', 'Murder', 'Sadistic Tendencies', 'Social abuse / Mental abuse chapter 48', 'Self-Insert', '(It\'s not but it\'s close enough so I was told too add it.)', 'Silly', 'Serious', 'Kuchiyose no Jutsu | Summoning Technique', 'Isekai', 'Kinda Sage Mode', 'Uzumaki Naruto', \"Hatake Kakashi & Hatake Kakashi's Mother\", 'Teuchi (Naruto)']",
     "genres":"['Naruto (Anime & Manga)', '?']"
    }
]

print(sample_bookmark_data[0]["author_name"])



sceneohscene


In [ ]:
# Importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import faiss

In [20]:
sk.__version__

'1.4.2'

In [23]:
# Creating a list of dictionaries
df_data = []
for data in sample_bookmark_data:
    df_data.append({
        "author's name": data["author_name"],
        "Tags": data["tags"],
        "Genre":data["genres"]
    })

# Create the DataFrame
df = pd.DataFrame(df_data)

# Display the DataFrame
print(df)

         author's name                                               Tags  \
0         sceneohscene  ['Creator Chose Not To Use Archive Warnings', ...   
1    miamourstarchaser  ['Graphic Depictions Of Violence', 'Major Char...   
2        iiSaturnGhxst  ['Major Character Death', 'No Archive Warnings...   
3  ShatteredSilverIris  ['Creator Chose Not To Use Archive Warnings', ...   
4         MakerofTales  ['Graphic Depictions Of Violence', 'Major Char...   

                                               Genre  
0  ['Harry Potter - J. K. Rowling', 'Fear Street ...  
1  ['Harry Potter - J. K. Rowling', 'Fear Street ...  
2                   ['Harry Potter - J. K. Rowling']  
3                   ['Harry Potter - J. K. Rowling']  
4                    ['Naruto (Anime & Manga)', '?']  


In [24]:
sample_dataframe = pd.DataFrame(sample_bookmark_data)
sample_dataframe

author_name                                               tags  \
0         sceneohscene  ['Creator Chose Not To Use Archive Warnings', ...   
1    miamourstarchaser  ['Graphic Depictions Of Violence', 'Major Char...   
2        iiSaturnGhxst  ['Major Character Death', 'No Archive Warnings...   
3  ShatteredSilverIris  ['Creator Chose Not To Use Archive Warnings', ...   
4         MakerofTales  ['Graphic Depictions Of Violence', 'Major Char...   

                                              genres  
0  ['Harry Potter - J. K. Rowling', 'Fear Street ...  
1  ['Harry Potter - J. K. Rowling', 'Fear Street ...  
2                   ['Harry Potter - J. K. Rowling']  
3                   ['Harry Potter - J. K. Rowling']  
4                    ['Naruto (Anime & Manga)', '?']

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer_author = TfidfVectorizer()
author_matrix = vectorizer_author.fit_transform(sample_dataframe["author_name"])
tfidf_df_1 = pd.DataFrame(author_matrix.toarray(), columns=vectorizer_author.get_feature_names_out())
print(tfidf_df_1)

   iisaturnghxst  makeroftales  miamourstarchaser  sceneohscene  \
0            0.0           0.0                0.0           1.0   
1            0.0           0.0                1.0           0.0   
2            1.0           0.0                0.0           0.0   
3            0.0           0.0                0.0           0.0   
4            0.0           1.0                0.0           0.0   

   shatteredsilveriris  
0                  0.0  
1                  0.0  
2                  0.0  
3                  1.0  
4                  0.0  


In [11]:
!pip install faiss-cpu


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 27.7 MB/s eta 0:00:00a 0:00:01


In [17]:

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import faiss

# Sample bookmark data
sample_bookmark_data = [
    {"author_name":"sceneohscene", 
     "tags":"['Creator Chose Not To Use Archive Warnings', 'Donna Paulsen & Harvey Specter', 'Louis Litt & Mike Ross', 'Louis Litt & Harvey Specter', 'Louis Litt & Donna Paulsen', 'Mike Ross & Rachel Zane', 'Donna Paulsen', 'Harvey Specter', 'Rachel Zane', 'Mike Ross', 'Louis Litt', 'Original Female Character(s)', 'Married Couple', 'Friendship', 'Birthday Presents', 'Best Friends', 'Team as Family', 'Family Fluff', 'One Shot Collection', 'Suits (US TV)', 'Harvey Specter', 'Team as Family', 'Friendship']", 
     "genres":"['Harry Potter - J. K. Rowling', 'Fear Street Trilogy (Movies 2021)']"
    },
    {"author_name":"miamourstarchaser",
     "tags":"['Graphic Depictions Of Violence', 'Major Character Death', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Alice Longbottom/Frank Longbottom', 'Barty Crouch Jr./Evan Rosier', 'Draco Malfoy/Harry Potter', 'Sirius Black', 'Regulus Black', 'James Potter', 'Remus Lupin', 'Frank Longbottom', 'Alice Longbottom', 'Barty Crouch Jr.', 'Evan Rosier', 'Draco Malfoy', 'Harry Potter', 'Hermione Granger', 'Ron Weasley', 'Marauders Era (Harry Potter)', 'Movie: Fear Street Part 2: 1978', 'Crossover', 'Alternate Universe', 'Summer Camp', 'Horror', 'Murder', 'Brother Angst', \"I've been watching fear street pt 2 every day this week\", 'Jegulus', 'wolfstar', 'Fralice', 'Rosekiller', 'Drarry', 'Alternate Universe', 'Marauders Era (Harry Potter)', 'Horror']",
     "genres":"['Harry Potter - J. K. Rowling', 'Fear Street Trilogy (Movies 2021)']"
    },
    {"author_name":"iiSaturnGhxst",
     "tags":"['Major Character Death', 'No Archive Warnings Apply', 'Sirius Black/Remus Lupin', 'Sirius Black & Remus Lupin', 'Harry Potter & Severus Snape', 'Luna Lovegood/Harry Potter', 'Sirius Black & James Potter', 'James Potter', 'Sirius Black', 'Hermione Granger', 'Remus Lupin', 'Molly Weasley', 'Ron Weasley', 'Arthur Weasley', 'Weasley Family (Harry Potter)', 'Severus Snape', 'Albus Dumbledore', 'Professor McGonagall', 'Dolores Umbridge', 'Nymphadora Tonks', 'Luna Lovegood', 'Harry Potter', 'Dursley Family (Harry Potter)', 'Abused Harry Potter', 'Depressed Harry Potter', 'Worried James Potter', 'Albus Dumbledore Bashing', 'Molly Weasley Bashing', 'It Gets Worse Before It Gets Better', 'Order of the Phoenix (Harry Potter)', 'Abused Harry Potter', 'Depressed Harry Potter', 'Albus Dumbledore Bashing', 'Order of the Phoenix (Harry Potter)']",
     "genres":"['Harry Potter - J. K. Rowling']"
    },
    {"author_name":"ShatteredSilverIris",
     "tags":"['Creator Chose Not To Use Archive Warnings', 'Regulus Black/James Potter', 'Sirius Black/Remus Lupin', 'Barty Crouch Jr./Evan Rosier', 'Regulus Black & Remus Lupin', 'Minor or Background Relationship(s)', 'Regulus Black', 'James Potter', 'Sirius Black', 'Remus Lupin', 'Peter Pettigrew', 'Evan Rosier', 'Barty Crouch Jr.', 'Lily Evans Potter', 'Marlene McKinnon', 'Pandora Lovegood', 'Dorcas Meadowes', 'Mary Macdonald (Harry Potter)', 'Severus Snape', 'Enemies to Lovers', 'Blind Character', 'Scars', 'Drinking Games', 'Truth or Dare', 'Spin the Bottle', 'Abusive Walburga Black', 'Abusive Parents', 'Alcohol', 'Cigarettes', 'Sad Regulus Black', 'Good Friend Barty Crouch Jr.', 'Good Friend Evan Rosier', 'Sibling Bonding', 'Regulus Black Needs a Hug', 'Non-binary Sirius Black', 'Sexuality Crisis', 'Gender Identity', 'Asexual Peter Pettigrew', 'Good Friend Remus Lupin', 'Hogwarts Inter-House Unity', 'Friends to Lovers', 'First Kiss', 'Platonic Kissing', 'Remus Lupin is So Done', 'Regulus Black & Remus Lupin Friendship', 'Brotherly Bonding', 'Barty Crouch Jr. is a Little Shit', 'Sirius Black is a Little Shit', 'Protective Sirius Black', 'Oblivious Remus Lupin', 'Oblivious Sirius Black', 'No beta we die like the marauders', 'Alternate Universe - No Voldemort', 'Never Have I Ever', 'Alternate Universe - Everyone Lives/Nobody Dies', 'We do not support jkr', 'Pottercest (Harry Potter)', 'Sirius Black/Remus Lupin', 'Severus Snape']",
     "genres":"['Harry Potter - J. K. Rowling']"
    },
    {"author_name":"MakerofTales",
     "tags":"['Graphic Depictions Of Violence', 'Major Character Death', 'Underage', 'Namikaze Minato/Uzumaki Kushina', 'Naruko Uzumaki & Her ANBU', 'Uzumaki Naruko', 'Hatake Kakashi', 'Sarutobi Hiruzen', 'Senju Hashirama', 'Teuchi (Naruto)', 'Jiraiya (Naruto)', 'Shimura Danzou', 'Yamato | Tenzou', 'Nagato | Pain', 'Zetsu (Naruto)', 'Namiashi Raidou', 'Namikaze Minato', 'Uchiha Itachi', 'Shiranui Genma', 'Anbu Characters (Naruto)', 'Original Anbu Character(s) (Naruto)', 'Hyuuga Hinata', 'Aburame Shino', 'Uchiha Sasuke', 'Ami (Naruto)', 'Nara Shikamaru', 'Akimichi Chouji', 'Umino Iruka', 'Oonoki (Naruto)', 'A | Fourth Raikage', 'Killer Bee (Naruto)', 'Terumi Mei', 'Karatachi Yagura', 'Sai (Naruto)', 'Haruno Sakura', 'Tobi (Naruto)', 'Reincarnation', 'Alternate Universe', 'Crossover', 'Cross-Posted on FanFiction.Net', 'Genderbending', 'Training', 'Chakra (Naruto)', 'Female Uzumaki Naruto', 'Academy', 'War', 'Jinchuuriki (Naruto)', 'Insanity', 'Bijuu | Tailed Beasts (Naruto)', 'Alternate Universe - Canon Divergence', 'Minato Namikaze is insane', 'Naruko is Insane', 'Ramen', 'Genius Naruko Uzumaki', 'Tricky Naruko Uzumaki', 'Henge no Jutsu | Transformation Technique', 'Kage Bunshin | Shadow Clones', 'Shinobi', 'Shinobi Politics (Naruto)', 'Infiltration', 'Murder', 'Sadistic Tendencies', 'Social abuse / Mental abuse chapter 48', 'Self-Insert', '(It\'s not but it\'s close enough so I was told too add it.)', 'Silly', 'Serious', 'Kuchiyose no Jutsu | Summoning Technique', 'Isekai', 'Kinda Sage Mode', 'Uzumaki Naruto', \"Hatake Kakashi & Hatake Kakashi's Mother\", 'Teuchi (Naruto)']",
     "genres":"['Naruto (Anime & Manga)', '?']"
    }
]

# Combining author's name, tags, and genres into separate strings for each bookmark
df['author_combined'] = df['author_name']
df['tags_combined'] = df['tags'].apply(lambda tags: ' '.join(tags))
df['genres_combined'] = df['genres'].apply(lambda genres: ' '.join(genres))

# Initializing TfidfVectorizer for each component
vectorizer_author = TfidfVectorizer()
vectorizer_tags = TfidfVectorizer()
vectorizer_genres = TfidfVectorizer()

# Transforming the combined strings into vectors
tfidf_author_matrix = vectorizer_author.fit_transform(df['author_combined'])
tfidf_tags_matrix = vectorizer_tags.fit_transform(df['tags_combined'])
tfidf_genres_matrix = vectorizer_genres.fit_transform(df['genres_combined'])

# Converting the matrices to arrays
tfidf_author_array = tfidf_author_matrix.toarray()
tfidf_tags_array = tfidf_tags_matrix.toarray()
tfidf_genres_array = tfidf_genres_matrix.toarray()

# Concatenate the vectors for each bookmark
combined_vectors = np.hstack([tfidf_author_array, tfidf_tags_array, tfidf_genres_array])

print(tfidf_tags_array, "\n") # vector for tags
print(tfidf_genres_array, "\n")
tfidf_author_array




[[0.43551029 0.         0.         0.43551029 0.         0.5082251
  0.         0.60197078 0.         0.         0.        ]
 [0.41447556 0.         0.         0.41447556 0.         0.
  0.         0.         0.57289616 0.57289616 0.        ]
 [0.38484912 0.64870321 0.         0.38484912 0.         0.
  0.         0.         0.         0.         0.53194592]
 [0.40216571 0.         0.55588125 0.         0.         0.46931314
  0.         0.         0.         0.         0.55588125]
 [0.         0.         0.44836665 0.         0.54677906 0.
  0.54677906 0.44836665 0.         0.         0.        ]
 [0.         0.         0.         0.40216571 0.         0.46931314
  0.         0.         0.55588125 0.55588125 0.        ]] 

[[0.56726902 0.         0.48988217 0.66198287 0.         0.
  0.         0.         0.        ]
 [0.46691105 0.         0.40321504 0.         0.78702713 0.
  0.         0.         0.        ]
 [0.         0.         0.38819592 0.52457317 0.         0.75771163
  0.  

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
dimension_author = tfidf_author_array.shape[1]
dimension_tags = tfidf_tags_array.shape[1]
dimension_genres = tfidf_genres_array.shape[1]

index_author = faiss.IndexFlatL2(dimension_author)
index_tags = faiss.IndexFlatL2(dimension_tags)
index_genres = faiss.IndexFlatL2(dimension_genres)

index_author.add(tfidf_author_array.astype(np.float32))
index_tags.add(tfidf_tags_array.astype(np.float32))
index_genres.add(tfidf_genres_array.astype(np.float32))

query_author_vector = tfidf_author_array[0].reshape(1, -1).astype(np.float32)
query_tags_vector = tfidf_tags_array[0].reshape(1, -1).astype(np.float32)
query_genres_vector = tfidf_genres_array[0].reshape(1, -1).astype(np.float32)

k = 5  # Number of similar items to retrieve

# similarity search for both distance and index
distances_author, author_indices = index_author.search(query_author_vector, k)
distances_tags, tags_indices = index_tags.search(query_tags_vector, k)
distances_genres, genres_indices = index_genres.search(query_genres_vector, k)

# Print results
print("Similar authors vectors:")
print(tfidf_author_array[author_indices.flatten()])
print("\nSimilar tags vectors:")
print(tfidf_tags_array[tags_indices.flatten()])
print("\nSimilar genres vectors:")
print(tfidf_genres_array[genres_indices.flatten()])


print("\nDistances for authors:")
print(distances_author.flatten())
print("\nDistances for tags:")
print(distances_tags.flatten())
print("\nDistances for genres:")
print(distances_genres.flatten())

Similar authors vectors:
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

Similar tags vectors:
[[0.43551029 0.         0.         0.43551029 0.         0.5082251
  0.         0.60197078 0.         0.         0.        ]
 [0.40216571 0.         0.55588125 0.         0.         0.46931314
  0.         0.         0.         0.         0.55588125]
 [0.         0.         0.         0.40216571 0.         0.46931314
  0.         0.         0.55588125 0.55588125 0.        ]
 [0.41447556 0.         0.         0.41447556 0.         0.
  0.         0.         0.57289616 0.57289616 0.        ]
 [0.38484912 0.64870321 0.         0.38484912 0.         0.
  0.         0.         0.         0.         0.53194592]]

Similar genres vectors:
[[0.56726902 0.         0.48988217 0.66198287 0.         0.
  0.         0.         0.        ]
 [0.         0.         0.38819592 0.52457317 0.         0.75771163
  0.         0.         0.        ]
 [0.         0.         0.38819592 0.52457317 0.    

In [21]:
# converting the similar vectors back into words

In [20]:
inverse_author_vectors = vectorizer_author.inverse_transform(tfidf_author_array[author_indices.flatten()])
inverse_tags_vectors = vectorizer_tags.inverse_transform(tfidf_tags_array[tags_indices.flatten()])
inverse_genres_vectors = vectorizer_genres.inverse_transform(tfidf_genres_array[genres_indices.flatten()])


similar_authors = [', '.join(authors) for authors in inverse_author_vectors]
similar_tags = [', '.join(tags) for tags in inverse_tags_vectors]
similar_genres = [', '.join(genres) for genres in inverse_genres_vectors]


print("Similar authors:")
print(similar_authors)
print("\nSimilar tags:")
print(similar_tags)
print("\nSimilar genres:")
print(similar_genres)

Similar authors:
['john', 'john', 'john', 'mike', 'harvey']

Similar tags:
['t1, t2, t3, t4', 't1, t12, t3, t9', 't2, t3, t5, t6', 't1, t2, t5, t6', 't1, t10, t2, t9']

Similar genres:
['g1, g2, g3', 'g2, g3, g5', 'g2, g3, g7', 'g1, g2, g4', 'g1, g2, g8']


# Another approach to solve this problem without using ML


In [2]:
import pandas as pd
from collections import Counter

# Sample bookmark data
sample_bookmark_data = [
    {"author_name": "john", "tags": ["t1", "t2", "t3", "t4"], "genres": ["g1", "g2", "g3"]},
    {"author_name": "mike", "tags": ["t1", "t2", "t5", "t6"], "genres": ["g1", "g2", "g4"]},
    {"author_name": "harvey", "tags": ["t1", "t2", "t10", "t9"], "genres": ["g2", "g5", "g3"]},
    {"author_name": "john", "tags": ["t1", "t3", "t12", "t9"], "genres": ["g2", "g3", "g7"]},
    {"author_name": "john", "tags": ["t12", "t34", "t21", "t4"], "genres": ["g1", "g2", "g8"]},
    {"author_name": "mike", "tags": ["t2", "t3", "t6", "t5"], "genres": ["g1", "g10", "g9"]}
]


df = pd.DataFrame(sample_bookmark_data)

# Extract authors, tags, and genres into separate lists
authors = df['author_name'].tolist()
tags = [tag for sublist in df['tags'].tolist() for tag in sublist]
genres = [genre for sublist in df['genres'].tolist() for genre in sublist]

# Calculate the frequency of each author, tag, and genre
author_freq = Counter(authors)
tags_freq = Counter(tags)
genres_freq = Counter(genres)

# Identify the most frequent authors, tags, and genres
most_common_authors = author_freq.most_common()
most_common_tags = tags_freq.most_common()
most_common_genres = genres_freq.most_common()

# Function to get top n items from a list of tuples
def get_top_n_items(item_list, n=5):
    return [item for item, count in item_list[:n]]

# Get top 3 most common authors, tags, and genres
top_authors = get_top_n_items(most_common_authors, n=3)
top_tags = get_top_n_items(most_common_tags, n=3)
top_genres = get_top_n_items(most_common_genres, n=3)

print("Top Authors:", top_authors)
print("Top Tags:", top_tags)
print("Top Genres:", top_genres)


Top Authors: ['john', 'mike', 'harvey']
Top Tags: ['t1', 't2', 't3']
Top Genres: ['g2', 'g1', 'g3']
